Repository WildCodeSchool/2023-02-Orleans-Spe-P2-A, pull requests merged in 2023-03, with the labels that each got.

#1 Initialisation of npm and the install of http-server
  .gitignore
  package-lock.json
  package.json
Labels: Reviewed, Change has been made.

#4 Created the end page
  src/config.js
  src/js/CatShoot.js
  src/js/EndGame.js
Labels: Need Review

#5 Pong game
  index.html
  package-lock.json
  package.json
  src/assets/font/street.ttf
  src/assets/img/paddle.png
  src/assets/img/platform.png
  src/assets/img/pong_ball.png
  src/assets/img/wall.png
  src/assets/pong_sound/beeep.ogg
  src/assets/pong_sound/peeeeeep.ogg
  src/assets/pong_sound/plop.ogg
  src/config.js
  src/js/CatShoot.js
  src/js/Pong.js
  src/js/Start.js
Labels: Reviewed, Change has been made.

#6 fix audio of pong game
  .gitignore
  src/js/CatShoot.js
  src/js/EndGame.js
  src/js/Pong.js
  src/js/Start.js
Labels: Reviewed, Change has been made.

#11 Fix pong timer and speed
  src/js/Pong.js
Labels: Reviewed
